mkobuolys/flutter_deck

CHANGELOG.md, README.md, lib/src/flutter_deck_configuration.dart, lib/src/flutter_deck_slide.dart, lib/src/widgets/internal/flutter_deck_progress_indicator.dart, lib/src/widgets/internal/internal.dart
Added presentation progress indicator (enabled by default).
=> feat: add presentation progress indicator

CHANGELOG.md, README.md
Update split slide documentation in README.md to highlight the text styling part.
=> docs: update split slide documentation

CHANGELOG.md, lib/src/templates/image_slide.dart, lib/src/theme/flutter_deck_theme.dart, lib/src/theme/templates/flutter_deck_image_slide_theme.dart, lib/src/theme/templates/templates.dart
Adds an image slide theme that allows styling the label.
=> feat: add image slide theme

README.md
Resolves https://github.com/mkobuolys/flutter_deck/issues/19
=> Add presentation example

CHANGELOG.md, lib/flutter_deck.dart
Fixes https://github.com/mkobuolys/flutter_deck/issues/31
=> fix: export SplitSlideRatio class from the framework

README.md
**READY**
Added a new presentation to those made with flutter_deck
=> add: New presentation built with flutter_deck

.github/workflows/deploy-example.yaml, example/web/index.html
Deploy the example page to GitHub Pages.
=> ci: add deploy-example workflow

CHANGELOG.md, README.md, example/lib/main.dart, example/macos/Runner.xcodeproj/project.pbxproj, example/macos/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme, lib/src/flutter_deck_app.dart, pubspec.yaml
Adds an option to run the app in scaled mode by keeping the specified aspect ratio.
=> feat: allow running FlutterDeckApp in scaled mode

CHANGELOG.md, example/lib/main.dart, lib/src/flutter_deck_slide.dart, lib/src/widgets/internal/controls/flutter_deck_controls.dart, pubspec.yaml
Fixes styling issues of the control widget and default slide background.
=> fix: adjust control widget styling and the default slide background color

README.md
Adding my Master's Thesis presentation to the list of examples at the bottom of the README. It has some interactive components and other goodies.
=> docs: add ReArch example presentation

CHANGELOG.md, README.md, lib/src/controls/flutter_deck_controls.dart, lib/src/controls/flutter_deck_controls_configuration.dart, lib/src/controls/flutter_deck_controls_listener.dart, lib/src/controls/localized_shortcut_labeler.dart
Fixes https://github.com/mkobuolys/flutter_deck/issues/25. Also, a breaking change was introduced that allows users to use key combinations with their modifiers as shortcuts.
=> fix: keyboard shortcuts not working properly

CHANGELOG.md, lib/src/widgets/flutter_deck_bullet_list.dart
Fixes FlutterDeckBulletList scaling issues when the `useSteps` flag is true.
=> fix: FlutterDeckBulletList scaling issues

CHANGELOG.md, lib/src/widgets/flutter_deck_footer.dart
=> fix: ignore unnecessary_import lint rule

README.md, cspell/authors.txt
**READY**
Thank you for the awesome package and I've published my slide deck built with flutter_deck, that's localized in Japanese and English.  
I'm glad if you add the link in your `README.md`.
=> docs: Added my slide with flutter_deck

packages/flutter_deck/CHANGELOG.md, packages/flutter_deck/lib/src/widgets/flutter_deck_code_highlight.dart
Adds a `textStyle` property to the `FlutterDeckCodeHighlight` widget.
Duplicates https://github.com/mkobuolys/flutter_deck/pull/72/files. After the recent repository restructure, it was easier to create a new PR.
=> feat(flutter_deck): add textStyle property to the FlutterDeckCodeHighlight widget

README.md
**READY**
Hey @mkobuolys love your package! I tried some fun things with your package like rendering a Flutter app inside my flutter_deck presentation. Take a look at the presentation. I was a bit disappointed of the capabilities of the code renderer. I would like to contribute and use another (better) package which I used in my presentation. Let me know if you are interested!
https://dario-digregorio.github.io/flutter_responsive/#/intro
=> added Dario Digregorio flutter_responsive url

packages/flutter_deck/CHANGELOG.md, packages/flutter_deck/lib/src/presenter/widgets/flutter_deck_presenter_slide_preview.dart
Implements https://github.com/mkobuolys/flutter_deck/issues/84
=> feat: Add slide number to the presenter view

packages/flutter_deck/CHANGELOG.md, packages/flutter_deck/pubspec.yaml, packages/flutter_deck_client/CHANGELOG.md, packages/flutter_deck_client/pubspec.yaml, packages/flutter_deck_web_client/CHANGELOG.md, packages/flutter_deck_web_client/pubspec.yaml, packages/flutter_deck_ws_client/CHANGELOG.md, packages/flutter_deck_ws_client/pubspec.yaml, packages/flutter_deck_ws_server/pubspec.yaml, pubspec.yaml
- Updates go_router to v14.2.0
- Updates very_good_analysis to v6.0.0
=> chore: update go_router and very_good_analysis dependencies

.github/workflows/main.yaml, packages/flutter_deck/CHANGELOG.md, packages/flutter_deck/lib/src/widgets/flutter_deck_header.dart
Fixes the maximum width problem for the slide header on window resize. It should remain the same.
=> fix(flutter_deck): header max width on window resize

README.md
**READY**
Adding a new talk into the examples table 🔥
=> doc: Add my state restoration talk to examples

.github/workflows/pull-request.yaml, melos.yaml, packages/flutter_deck/example/test/make_ci_happy_test.dart, packages/flutter_deck_client/pubspec.yaml, packages/flutter_deck_client/test/make_ci_happy_test.dart, packages/flutter_deck_web_client/pubspec.yaml, packages/flutter_deck_web_client/test/make_ci_happy_test.dart, packages/flutter_deck_ws_client/pubspec.yaml, packages/flutter_deck_ws_client/test/make_ci_happy_test.dart, packages/flutter_deck_ws_server/pubspec.yaml, packages/flutter_deck_ws_server/test/make_ci_happy_test.dart
Add some empty tests for the CI not to break PR flows.
=> test: add tests to make CI happy

doc/website/source/showcase.md
**READY**
Added my talk about asset transformation from Flutter Vienna meetup yesterday 👍🏽
=> docs: Add new talk to the showcase section

packages/flutter_deck_web_client/CHANGELOG.md, packages/flutter_deck_web_client/pubspec.yaml
Upgrades `web` dependency to v1.1.1 and fixes https://github.com/mkobuolys/flutter_deck/issues/120.
=> feat: upgrade web dependency

doc/website/source/guides/code-generation.md, doc/website/source/guides/creating-slides.md, doc/website/source/guides/hiding-slides.md, doc/website/source/guides/initial-slide.md, doc/website/source/guides/localization.md, doc/website/source/guides/presentation-state.md, doc/website/source/guides/slide-steps.md, doc/website/source/guides/transitions.md, doc/website/source/playback/auto-play.md, doc/website/source/playback/change-locale.md, doc/website/source/playback/marker-tool.md, doc/website/source/playback/navigation-drawer.md, doc/website/source/playback/presenter-view.md, doc/website/source/slide-templates/big-fact-slide.md, doc/website/source/slide-templates/blank-slide.md, doc/website/source/slide-templates/custom-slide.md, doc/website/source/slide-templates/image-slide.md, doc/website/source/slide-templates/quote-slide.md, doc/website/source/slide-templates/split-slide.md, doc/website/source/slide-templates/template-slide.md, doc/website/source/slide-templates/title-slide.md, packages/flutter_deck/CHANGELOG.md, packages/flutter_deck/lib/src/configuration/flutter_deck_configuration.dart, packages/flutter_deck/lib/src/flutter_deck_router.dart, packages/flutter_deck/pubspec.yaml
Implements https://github.com/mkobuolys/flutter_deck/issues/124
=> feat: set the initial slide for the deck

packages/flutter_deck_client/CHANGELOG.md, packages/flutter_deck_client/README.md, packages/flutter_deck_client/lib/src/flutter_deck_client.dart, packages/flutter_deck_client/pubspec.yaml
Adds the `openPresenterView` method to the `FlutterDeckClient` interface.
=> feat(flutter_deck_client): add openPresenterView method

packages/flutter_deck/lib/src/flutter_deck_app.dart, packages/flutter_deck/lib/src/flutter_deck_router.dart, packages/flutter_deck/test/src/flutter_deck_app_test.dart
=> feat: allow adding custom `NavigatorObservers` to `FlutterDeckApp`
